@startuml

class Person {
  String name
}

class Patient {
  UUID id
  Date dateOfBirth
  int getAge()
}
Patient --|> Person

class PatientService {
  patientRepository
  create(patient)
}
PatientService --> Patient

@enduml
